{{- /*
This secret is used to store the admin user account credentials for Grafana
*/ -}}
{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: prometheus
    heritage: {{ .Release.Service }}
    name: {{ .Release.Name }}-grafana
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-grafana
  namespace: {{ .Values.metadata.namespace }}
type: Opaque
data:
  admin-user: {{ .Values.prometheus.grafana.adminUser | b64enc | quote }}
  admin-password: {{ .Values.prometheus.grafana.adminPassword | b64enc | quote }}
{{- end -}}
