{{- /*
Exposes the Prometheus metrics explorer dashboard on the "prometheus-port"
Also exposes Grafana dashboards on the "grafana-port"
*/ -}}
{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.prometheus.service.annotations }}
  annotations:
{{ toYaml .Values.prometheus.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: prometheus
    heritage: {{ .Release.Service }}
    name: {{ .Release.Name }}-prometheus
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-prometheus
  namespace: {{ .Values.metadata.namespace }}
spec:
  type: {{ .Values.prometheus.service.type }}
  selector:
    app: prometheus
    name: {{ .Release.Name }}-prometheus
    release: {{ .Release.Name }}
  ports:
    - name: prometheus-port
      port: {{ .Values.prometheus.service.ports.prom }}
      protocol: TCP
      targetPort: 9090
  {{- if .Values.prometheus.service.ports.grafana }}
    - name: grafana-port
      port: {{ .Values.prometheus.service.ports.grafana }}
      protocol: TCP
      targetPort: 3000
  {{- end }}
{{- end -}}
