{{- /*
Assigns the "get", "watch", and "list" verbs to the Service Account used by Grafana to query for dasboards
*/ -}}
{{- if .Values.prometheus.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: prometheus
    heritage: {{ .Release.Service }}
    name: {{ .Release.Name }}-prometheus
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-prometheus
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-prometheus
  namespace: {{ .Values.metadata.namespace }}
{{- end -}}
