{{- /*
Service Account used by Grafana to query for dasboards from its own Helm Release in its Namespace only
*/ -}}
{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: prometheus
    heritage: {{ .Release.Service }}
    name: {{ .Release.Name }}-prometheus
    release: {{ .Release.Name }}
  name: {{ .Release.Name }}-prometheus
  namespace: {{ .Values.metadata.namespace }}
{{- end -}}
